// design-sync bundle entry for claude.ai/design.
// This repo is a Vite app with no library build, so the converter needs an
// explicit barrel to bundle into window.Mandrock0. It re-exports the real
// component sources verbatim — nothing is reimplemented here.
// Regenerate with: .design-sync/gen-entry.sh

export * from '../src/components/ui/accordion.tsx';
export * from '../src/components/ui/alert-dialog.tsx';
export * from '../src/components/ui/alert.tsx';
export * from '../src/components/ui/aspect-ratio.tsx';
export * from '../src/components/ui/attachment.tsx';
export * from '../src/components/ui/avatar.tsx';
export * from '../src/components/ui/badge.tsx';
export * from '../src/components/ui/breadcrumb.tsx';
export * from '../src/components/ui/bubble.tsx';
export * from '../src/components/ui/button-group.tsx';
export * from '../src/components/ui/button.tsx';
export * from '../src/components/ui/calendar.tsx';
export * from '../src/components/ui/card.tsx';
export * from '../src/components/ui/carousel.tsx';
export * from '../src/components/ui/chart.tsx';
export * from '../src/components/ui/checkbox.tsx';
export * from '../src/components/ui/collapsible.tsx';
export * from '../src/components/ui/combobox.tsx';
export * from '../src/components/ui/command.tsx';
export * from '../src/components/ui/context-menu.tsx';
export * from '../src/components/ui/dialog.tsx';
export * from '../src/components/ui/direction.tsx';
export * from '../src/components/ui/drawer.tsx';
export * from '../src/components/ui/dropdown-menu.tsx';
export * from '../src/components/ui/empty.tsx';
export * from '../src/components/ui/field.tsx';
export * from '../src/components/ui/hover-card.tsx';
export * from '../src/components/ui/input-group.tsx';
export * from '../src/components/ui/input-otp.tsx';
export * from '../src/components/ui/input.tsx';
export * from '../src/components/ui/item.tsx';
export * from '../src/components/ui/kbd.tsx';
export * from '../src/components/ui/label.tsx';
export * from '../src/components/ui/marker.tsx';
export * from '../src/components/ui/menubar.tsx';
export * from '../src/components/ui/message-scroller.tsx';
export * from '../src/components/ui/message.tsx';
export * from '../src/components/ui/native-select.tsx';
export * from '../src/components/ui/navigation-menu.tsx';
export * from '../src/components/ui/pagination.tsx';
export * from '../src/components/ui/popover.tsx';
export * from '../src/components/ui/progress.tsx';
export * from '../src/components/ui/radio-group.tsx';
export * from '../src/components/ui/resizable.tsx';
export * from '../src/components/ui/scroll-area.tsx';
export * from '../src/components/ui/select.tsx';
export * from '../src/components/ui/separator.tsx';
export * from '../src/components/ui/sheet.tsx';
export * from '../src/components/ui/sidebar.tsx';
export * from '../src/components/ui/skeleton.tsx';
export * from '../src/components/ui/slider.tsx';
export * from '../src/components/ui/sonner.tsx';
export * from '../src/components/ui/spinner.tsx';
export * from '../src/components/ui/switch.tsx';
export * from '../src/components/ui/table.tsx';
export * from '../src/components/ui/tabs.tsx';
export * from '../src/components/ui/textarea.tsx';
export * from '../src/components/ui/toggle-group.tsx';
export * from '../src/components/ui/toggle.tsx';
export * from '../src/components/ui/tooltip.tsx';
export * from '../src/components/debris/Debris.tsx';
